site_name: FlexiConc Documentation
site_url: https://fau-klue.github.io/flexiconc-docs
repo_url: https://github.com/fau-klue/flexiconc-docs  # Now points to the public repo
repo_name: flexiconc-docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../flexiconc]  # Points to your Python package

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started: getting-started.md
  - Concepts: concepts.md
  - Algorithms:
      - Overview: algorithms/index.md
      - Selecting: algorithms/select.md
      - Ordering: algorithms/order.md
      - Grouping: algorithms/group.md
  - Examples: examples/example-analysis.md
  - API Reference:
      - Concordance API: api/concordance.md
      - Analysis Tree: api/analysis-tree.md
      - Algorithms: api/algorithms.md
  - Changelog: changelog.md
